const PostCardActionTypes = {
  FETCH_POSTCARDS_START: 'FETCH_POSTCARDS_START',
  FETCH_POSTCARDS_SUCCESS: 'FETCH_POSTCARDS_SUCCESS',
  FETCH_POSTCARDS_FAILURE: 'FETCH_POSTCARDS_FAILURE',
  GET_SINGLE_POSTCARD: 'GET_SINGLE_POSTCARD',
  ADD_POSTCARDS: 'ADD_POSTCARDS',
  DELETE_POSTCARDS: 'DELETE_POSTCARDS',
  EDIT_POSTCARD: 'EDIT_POSTCARD'
}

export default PostCardActionTypes