const PostCardActionTypes = {
  FETCH_POSTCARDS_START: 'FETCH_POSTCARDS_START',
  FETCH_POSTCARDS_SUCCESS: 'FETCH_POSTCARDS_SUCCESS',
  FETCH_POSTCARDS_FAILURE: 'FETCH_POSTCARDS_FAILURE',
  ADD_POSTCARD_START: 'ADD_POSTCARD_START',
  ADD_POSTCARD_SUCCESS: 'ADD_POSTCARD_SUCCESS',
  ADD_POSTCARD_FAILURE: 'ADD_POSTCARD_FAILURE',
  GET_SINGLE_POSTCARD_START: 'GET_SINGLE_POSTCARD_START',
  GET_SINGLE_POSTCARD_SUCCESS: 'GET_SINGLE_POSTCARD_SUCCESS',
  DELETE_POSTCARD_START: 'DELETE_POSTCARD_START',
  DELETE_POSTCARD_SUCCESS: 'DELETE_POSTCARD_SUCCESS',
  DELETE_POSTCARD_FAILURE: 'DELETE_POSTCARD_FAILURE',
  EDIT_POSTCARD_START: 'EDIT_POSTCARD_START',
  EDIT_POSTCARD_SUCCESS: 'EDIT_POSTCARD_SUCCESS',
  EDIT_POSTCARD_FAILURE: 'EDIT_POSTCARD_FAILURE',
}

export default PostCardActionTypes