const PostCardActionTypes = {
  GET_POSTCARDS: 'GET_POSTCARDS',
  GET_SINGLE_POSTCARD: 'GET_SINGLE_POSTCARD',
  ADD_POSTCARDS: 'ADD_POSTCARDS',
  DELETE_POSTCARDS: 'DELETE_POSTCARDS',
  EDIT_POSTCARD: 'EDIT_POSTCARD'
}

export default PostCardActionTypes