const StickerActionTypes = {
  FETCH_STICKER_START: 'FETCH_STICKER_START',
  FETCH_STICKER_SUCCESS: 'FETCH_STICKER_SUCCESS',
  FETCH_STICKER_FAILURE: 'FETCH_STICKER_FAILURE',
  GET_STICKER: 'GET_STICKER',
  GET_SINGLE_STICKER: 'GET_SINGLE_STICKER',
  ADD_STICKER: 'ADD_STICKER',
  DELETE_STICKER: 'DELETE_STICKER',
  EDIT_STICKER: 'EDIT_STICKER'
}

export default StickerActionTypes