const StickerActionTypes = {
  FETCH_STICKER_START: 'FETCH_STICKER_START',
  FETCH_STICKER_SUCCESS: 'FETCH_STICKER_SUCCESS',
  FETCH_STICKER_FAILURE: 'FETCH_STICKER_FAILURE',
  ADD_STICKER_START: 'ADD_STICKER_START',
  ADD_STICKER_SUCCESS: 'ADD_STICKER_SUCCESS',
  ADD_STICKER_FAILURE: 'ADD_STICKER_FAILURE',
  GET_SINGLE_STICKER_START: 'GET_SINGLE_STICKER_START',
  GET_SINGLE_STICKER_SUCCESS: 'GET_SINGLE_STICKER_SUCCESS',
  DELETE_STICKER_START: 'DELETE_STICKER_START',
  DELETE_STICKER_SUCCESS: 'DELETE_STICKER_SUCCESS',
  DELETE_STICKER_FAILURE: 'DELETE_STICKER_FAILURE',
  EDIT_STICKER_START: 'EDIT_STICKER_START',
  EDIT_STICKER_SUCCESS: 'EDIT_STICKER_SUCCESS',
  EDIT_STICKER_FAILURE: 'EDIT_STICKER_FAILURE',
}

export default StickerActionTypes