const WishCardActionTypes = {
  FETCH_WISH_CARD_START: 'FETCH_WISH_CARD_START',
  FETCH_WISH_CARD_SUCCESS: 'FETCH_WISH_CARD_SUCCESS',
  FETCH_WISH_CARD_FAILURE: 'FETCH_WISH_CARD_FAILURE',
  ADD_WISH_CARD_START: 'ADD_WISH_CARD_START',
  ADD_WISH_CARD_SUCCESS: 'ADD_WISH_CARD_SUCCESS',
  ADD_WISH_CARD_FAILURE: 'ADD_WISH_CARD_FAILURE',
  GET_SINGLE_WISH_CARD_START: 'GET_SINGLE_WISH_CARD_START',
  GET_SINGLE_WISH_CARD_SUCCESS: 'GET_SINGLE_WISH_CARD_SUCCESS',
  DELETE_WISH_CARD_START: 'DELETE_WISH_CARD_START',
  DELETE_WISH_CARD_SUCCESS: 'DELETE_WISH_CARD_SUCCESS',
  DELETE_WISH_CARD_FAILURE: 'DELETE_WISH_CARD_FAILURE',
  EDIT_WISH_CARD_START: 'EDIT_WISH_CARD_START',
  EDIT_WISH_CARD_SUCCESS: 'EDIT_WISH_CARD_SUCCESS',
  EDIT_WISH_CARD_FAILURE: 'EDIT_WISH_CARD_FAILURE',
}

export default WishCardActionTypes