const WishCardActionTypes = {
  FETCH_WISH_CARD_START: 'FETCH_WISH_CARD_START',
  FETCH_WISH_CARD_SUCCESS: 'FETCH_WISH_CARD_SUCCESS',
  FETCH_WISH_CARD_FAILURE: 'FETCH_WISH_CARD_FAILURE',
  ADD_WISH_CARD: 'ADD_WISH_CARD',
  GET_SINGLE_WISH_CARD: 'GET_SINGLE_WISH_CARD',
  DELETE_WISH_CARD: 'DELETE_WISH_CARD',
  EDIT_WISH_CARD: 'EDIT_WISH_CARD'
}

export default WishCardActionTypes