const CharacterActionTypes = {
  FETCH_CHARACTER_START: 'FETCH_CHARACTER_START',
  FETCH_CHARACTER_SUCCESS: 'FETCH_CHARACTER_SUCCESS',
  FETCH_CHARACTER_FAILURE: 'FETCH_CHARACTER_FAILURE',
  GET_CHARACTER: 'GET_CHARACTER',
  GET_SINGLE_CHARACTER: 'GET_SINGLE_CHARACTER',
  ADD_CHARACTER: 'ADD_CHARACTER',
  DELETE_CHARACTER: 'DELETE_CHARACTER',
  EDIT_CHARACTER: 'EDIT_CHARACTER'
}

export default CharacterActionTypes