const CharacterActionTypes = {
  FETCH_CHARACTER_START: 'FETCH_CHARACTER_START',
  FETCH_CHARACTER_SUCCESS: 'FETCH_CHARACTER_SUCCESS',
  FETCH_CHARACTER_FAILURE: 'FETCH_CHARACTER_FAILURE',
  ADD_CHARACTER_START: 'ADD_CHARACTER_START',
  ADD_CHARACTER_SUCCESS: 'ADD_CHARACTER_SUCCESS',
  ADD_CHARACTER_FAILURE: 'ADD_CHARACTER_FAILURE',
  GET_SINGLE_CHARACTER_START: 'GET_SINGLE_CHARACTER_START',
  GET_SINGLE_CHARACTER_SUCCESS: 'GET_SINGLE_CHARACTER_SUCCESS',
  DELETE_CHARACTER_START: 'DELETE_CHARACTER_START',
  DELETE_CHARACTER_SUCCESS: 'DELETE_CHARACTER_SUCCESS',
  DELETE_CHARACTER_FAILURE: 'DELETE_CHARACTER_FAILURE',
  EDIT_CHARACTER_START: 'EDIT_CHARACTER_START',
  EDIT_CHARACTER_SUCCESS: 'EDIT_CHARACTER_SUCCESS',
  EDIT_CHARACTER_FAILURE: 'EDIT_CHARACTER_FAILURE',
}

export default CharacterActionTypes