const CharacterActionTypes = {
  GET_CHARACTER: 'GET_CHARACTER',
  GET_SINGLE_CHARACTER: 'GET_SINGLE_CHARACTER',
  ADD_CHARACTER: 'ADD_CHARACTER',
  DELETE_CHARACTER: 'DELETE_CHARACTER',
  EDIT_CHARACTER: 'EDIT_CHARACTER'
}

export default CharacterActionTypes